import { WORLD, VIEWPORT, LEVELS, newRun, nextLevel, step, cameraFor, smoothCamera, BOUNCE, BOMB, requestJump as importedJump } from './game.js?v=20260926-5';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),levelText=$('#level'),livesText=$('#lives'),timerText=$('#timer'),notice=$('#notice'),tiltButton=$('#tilt'),tiltStatus=$('#tilt-status'),dpad=$('#dpad'),bounceButton=$('#bounce');
let run=newRun(),input={x:0,y:0},last=performance.now(),tiltActive=false,manualPause=false,menuOpen=false,phase='splash',audioOn=true,audio=null,failUntil=0,camera=cameraFor(run),transition=null,bouncePress=null,selectedDifficulty='standard';
const keys=new Set(),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),playing=()=>phase==='playing'&&!menuOpen&&!manualPause;
function sound(kind){if(!audioOn||!playing())return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g).connect(audio.destination);const map={jump:[330,.07,'square'],super:[660,.12,'sine'],pickup:[880,.1,'triangle'],hit:[90,.18,'sawtooth'],win:[520,.24,'sine']};const [f,d,t]=map[kind]||map.jump;o.frequency.setValueAtTime(f,audio.currentTime);if(kind==='hit')o.frequency.exponentialRampToValueAtTime(35,audio.currentTime+d);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.type=t;o.start();o.stop(audio.currentTime+d)}catch{audioOn=false;$('#audio').textContent='audio unavailable'}}
function music(){if(!audioOn||phase!=='playing')return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();if(audio._mm)return;audio._mm=setInterval(()=>{if(playing()&&run.status==='playing')sound('pickup')},1800)}catch{}}
function freezeAudio(){if(audio?.state==='running')audio.suspend().catch(()=>{})}function resumeAudio(){if(audioOn&&phase==='playing'&&!menuOpen&&!manualPause&&audio?.state==='suspended')audio.resume().catch(()=>{})}
function updateKeyboard(){input.x=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);input.y=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0)}
function jump(heldMs=0){if(!playing()||run.status!=='playing'||transition)return;const next=importedJump(run,heldMs);if(next===run)return;const distance=Math.round(Math.hypot(next.marble.x-run.marble.x,next.marble.y-run.marble.y));run=next;sound(next.jumpKind==='super'?'super':'jump');notice.textContent=`${next.jumpKind==='super'?'super · ':''}${heldMs>=BOUNCE.holdMs?'long':'tap'} ${(distance/WORLD.unit).toFixed(1)} units`;}

addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);updateKeyboard()}if(e.key===' '&&!e.repeat){e.preventDefault();bouncePress={keyboard:true,start:performance.now()}}if(e.key==='Escape'&&phase==='playing'){menuOpen=!menuOpen;syncMenu()}});addEventListener('keyup',e=>{keys.delete(e.key);updateKeyboard();if(e.key===' '&&bouncePress?.keyboard){jump(performance.now()-bouncePress.start);bouncePress=null}});
canvas.addEventListener('pointerdown',e=>{if(!playing()||tiltActive||transition)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*VIEWPORT.width,y=(e.clientY-r.top)/r.height*VIEWPORT.height;input={...input,x:Math.abs(x-VIEWPORT.width/2)>Math.abs(y-VIEWPORT.height/2)?Math.sign(x-VIEWPORT.width/2):0,y:Math.abs(y-VIEWPORT.height/2)>=Math.abs(x-VIEWPORT.width/2)?Math.sign(y-VIEWPORT.height/2):0};music()});canvas.addEventListener('pointerup',()=>{if(!tiltActive){input.x=0;input.y=0}});
function setTiltStatus(text){tiltStatus.textContent=text}
function syncPad(){dpad.classList.toggle('tilt-mode',tiltActive);dpad.setAttribute('aria-label',tiltActive?'bounce control':'touch movement and bounce controls');if(tiltActive){input.x=0;input.y=0}}
async function enableTilt(){try{if(typeof DeviceOrientationEvent==='undefined')throw Error('unavailable');if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error('denied');tiltActive=true;syncPad();tiltButton.textContent='tilt on';tiltButton.setAttribute('aria-pressed','true');setTiltStatus('tilt enabled — move R1 to steer');notice.textContent='tilt enabled'}catch{tiltActive=false;syncPad();tiltButton.textContent='tilt';tiltButton.setAttribute('aria-pressed','false');setTiltStatus('tilt unavailable — use arrows, WASD, or board edges');notice.textContent='tilt unavailable — fallback controls ready'}}
addEventListener('deviceorientation',e=>{if(!tiltActive||e.gamma==null||e.beta==null||!playing())return;input.x=clamp(e.gamma/25,-1,1);input.y=clamp(e.beta/25,-1,1)});
function showPhase(next){cancelBounce();phase=next;$('#splash').hidden=next!=='splash';$('#start-menu').hidden=next!=='menu';$('#hud').hidden=next!=='playing';tiltButton.hidden=next!=='playing';$('#waffle').hidden=next!=='playing';dpad.hidden=next!=='playing';notice.textContent='';if(next!=='playing')freezeAudio();syncMenu()}
function startGame(){run=newRun(0,selectedDifficulty);camera=cameraFor(run);manualPause=false;showPhase('playing');transition={kind:'enter',start:performance.now(),duration:650};notice.textContent=`enter ${LEVELS[0].name}`;music();resumeAudio();syncUI()}
function syncMenu(){if(menuOpen){cancelBounce();if(transition&&!transition.pausedAt)transition.pausedAt=performance.now()}else if(transition?.pausedAt){transition.start+=performance.now()-transition.pausedAt;transition.pausedAt=0}const visible=phase==='playing'&&menuOpen;$('#menu').hidden=!visible;$('#waffle').setAttribute('aria-expanded',String(visible));if(visible)freezeAudio();else resumeAudio();syncUI()}
function toggleMenu(){if(phase!=='playing')return;menuOpen=!menuOpen;syncMenu()}
function setPadDirection(direction, pressed){const vectors={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};const [x,y]=vectors[direction];if(pressed&&playing()&&!tiltActive){input.x=x;input.y=y;music()}else if(!tiltActive){input.x=0;input.y=0}}
for(const button of document.querySelectorAll('.pad-dir')){const direction=button.dataset.direction;button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);setPadDirection(direction,true)});for(const eventName of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(eventName,()=>setPadDirection(direction,false));}
function cancelBounce(){bouncePress=null;bounceButton.classList.remove('charging')}
bounceButton.addEventListener('pointerdown',event=>{event.preventDefault();if(!playing())return;bouncePress={id:event.pointerId,start:performance.now()};bounceButton.setPointerCapture?.(event.pointerId);bounceButton.classList.add('charging');music()});
bounceButton.addEventListener('pointerup',event=>{if(bouncePress?.id!==event.pointerId)return;const held=performance.now()-bouncePress.start;cancelBounce();jump(held)});
for(const name of ['pointercancel','lostpointercapture'])bounceButton.addEventListener(name,()=>cancelBounce());
tiltButton.onclick=enableTilt;$('#restart').onclick=()=>{cancelBounce();transition=null;run=newRun(0,selectedDifficulty);camera=cameraFor(run);input.x=0;input.y=0;manualPause=false;notice.textContent='';menuOpen=false;syncMenu();music()};$('#pause').onclick=()=>{cancelBounce();manualPause=!manualPause;if(manualPause)freezeAudio();else resumeAudio();syncUI()};$('#audio').onclick=()=>{audioOn=!audioOn;$('#audio').textContent=audioOn?'audio on':'audio off';if(audioOn){music();resumeAudio()}else freezeAudio()};$('#waffle').onclick=toggleMenu;$('#close-menu').onclick=toggleMenu;$('#resume').onclick=toggleMenu;$('#difficulty').onchange=e=>{selectedDifficulty=e.target.value};const continueToMenu=()=>showPhase('menu');$('#continue').onclick=continueToMenu;$('#splash').addEventListener('pointerup',e=>{if(phase==='splash'&&e.target!==$('#continue'))continueToMenu()});$('#start').onclick=startGame;$('#start-waffle').onclick=()=>{notice.textContent='options are available from the waffle during play'};$('#theme').onclick=()=>{const light=document.documentElement.dataset.theme==='light';document.documentElement.dataset.theme=light?'dark':'light';$('#theme').textContent=light?'light mode':'dark mode'};document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';
function syncUI(){const l=LEVELS[run.levelIndex];levelText.textContent=`${String(run.levelIndex+1).padStart(2,'0')} ${l.name}`;livesText.textContent='● '.repeat(run.lives).trim()||'—';timerText.textContent=run.remaining.toFixed(1);bounceButton.textContent=bouncePress?performance.now()-bouncePress.start>=BOUNCE.holdMs?'long':'hold':run.superJumps>0?`super ×${run.superJumps}`:'bounce';$('#effect').textContent=[run.bombs.some(b=>b.phase==='fuse')?'bomb! move away':null,run.gravity?'pull':null,run.terrain==='sand'?'sand slow':null,run.dizzy>0?'dizzy':null].filter(Boolean).join(' · ');bounceButton.setAttribute('aria-label',run.superJumps>0?'super bounce':'bounce');$('#pause').textContent=manualPause?'resume':'pause'}
function circle(x,y,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}function draw(){const css=getComputedStyle(document.documentElement),bg=css.getPropertyValue('--board'),line=css.getPropertyValue('--line'),accent=css.getPropertyValue('--accent'),text=css.getPropertyValue('--text');ctx.fillStyle=bg;ctx.fillRect(0,0,240,282);ctx.save();ctx.scale(240/VIEWPORT.width,282/VIEWPORT.height);ctx.translate(0,-camera);ctx.strokeStyle=line;ctx.lineWidth=1;for(let y=Math.floor(camera/22)*22;y<camera+VIEWPORT.height+22;y+=22){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.width,y);ctx.stroke()}for(let x=22;x<WORLD.width;x+=22){ctx.beginPath();ctx.moveTo(x,camera);ctx.lineTo(x,camera+VIEWPORT.height);ctx.stroke()}const l=LEVELS[run.levelIndex];ctx.fillStyle=text;l.obstacles.forEach(r=>{ctx.fillStyle=r.type==='half'?'#f9c64b':r.type==='rebound'?'#52e0dd':text;ctx.fillRect(r.x,r.y,r.w,r.h);if(r.type==='rebound'){ctx.fillStyle='#163d45';for(let x=r.x+4;x<r.x+r.w-3;x+=12)ctx.fillRect(x,r.y+4,5,r.h-8)}});
  l.features.forEach(f=>{if(f.type==='pit'){if(run.difficulty==='beginner')return;ctx.strokeStyle='#b66ad0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y,f.r+8,0,Math.PI*1.7);ctx.stroke();circle(f.x,f.y,f.r+3,'#c45bdb');circle(f.x,f.y,f.r,'#040308');circle(f.x-5,f.y-6,2,'#86539d')}else if(f.type==='sand'){circle(f.x,f.y,f.r,'#b69351');circle(f.x-6,f.y+4,2,'#f4dc91')}else if(f.type==='merry'){circle(f.x,f.y,f.r,'#64b7cf');ctx.strokeStyle='#fff';ctx.beginPath();ctx.arc(f.x,f.y,11,performance.now()/500,performance.now()/500+4);ctx.stroke()}else if(f.type==='ice'){circle(f.x,f.y,f.r,'#85d8f0');ctx.fillStyle='#fff';ctx.fillRect(f.x-9,f.y-2,17,2)}else if(f.type==='sticky'){circle(f.x,f.y,f.r,'#9b7a42');circle(f.x+4,f.y-3,4,'#513c29')}else if(f.type==='bumper'){circle(f.x,f.y,f.r+2,'#68e5dd');circle(f.x,f.y,f.r-5,'#116f80')}else{circle(f.x,f.y,f.r,'#dc5252');ctx.fillStyle='#fff';ctx.fillText('✦',f.x-8,f.y+6)}});
  run.bombs.forEach(b=>{if(b.phase==='spent')return;const armed=b.phase==='fuse',burst=b.phase==='blast';ctx.strokeStyle=burst?'#fff4ad':armed?'#ffb12b':'#fca751';ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,burst?BOMB.blastRadius:armed?BOMB.triggerRadius:b.r+3,0,Math.PI*2);ctx.stroke();circle(b.x,b.y,b.r,burst?'#ffe6a2':'#24232b');ctx.fillStyle='#fff';ctx.font='bold 15px Helvetica';ctx.fillText('✹',b.x-8,b.y+5);ctx.fillStyle='#ffad30';ctx.fillRect(b.x-2,b.y-b.r-5,4,5);if(armed){ctx.fillStyle='#fff';ctx.font='bold 10px Helvetica';ctx.fillText(String(Math.ceil(b.time*10)/10),b.x-8,b.y-17)}});
  circle(l.goal.x,l.goal.y,WORLD.goalRadius,accent);ctx.fillStyle=text;ctx.font='20px Helvetica';ctx.fillText('exit',l.goal.x-18,l.goal.y+6);run.powerups.forEach(p=>{if(!p.collected){circle(p.x,p.y,14,accent);ctx.fillStyle=bg;ctx.font='20px Helvetica';ctx.fillText('★',p.x-10,p.y+7)}});run.enemies.forEach(e=>{circle(e.x,e.y,e.r,'#a83243');circle(e.x-5,e.y-2,3,'#fff');circle(e.x+5,e.y-2,3,'#fff');circle(e.x-4,e.y-1,1.5,'#180a18');circle(e.x+4,e.y-1,1.5,'#180a18');ctx.strokeStyle='#210b1a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.x-9,e.y-8);ctx.lineTo(e.x-2,e.y-5);ctx.moveTo(e.x+9,e.y-8);ctx.lineTo(e.x+2,e.y-5);ctx.moveTo(e.x-5,e.y+8);ctx.quadraticCurveTo(e.x,e.y+3,e.x+5,e.y+8);ctx.stroke()});if(run.airborne>0)circle(run.marble.x,run.marble.y+10,10,'rgba(0,0,0,.35)');const g=ctx.createRadialGradient(run.marble.x-5,run.marble.y-6,2,run.marble.x,run.marble.y,14);g.addColorStop(0,'#fff');g.addColorStop(.25,'#ffe234');g.addColorStop(.6,'#ff4612');g.addColorStop(1,'#6f35ff');circle(run.marble.x,run.marble.y-(run.airborne>0?12:0),WORLD.marbleRadius,g);if(performance.now()<failUntil){const t=(failUntil-performance.now())/600;ctx.globalAlpha=t;ctx.fillStyle=accent;if(run.failure==='explode'){for(let i=0;i<12;i++){const a=i*Math.PI/6;circle(run.marble.x+Math.cos(a)*(1-t)*70,run.marble.y+Math.sin(a)*(1-t)*70,7,accent)}}else if(run.failure==='crumble'){for(let i=0;i<8;i++)ctx.fillRect(run.marble.x-24+i*6,run.marble.y+(1-t)*45+(i%2)*8,5,5)}else ctx.fillRect(run.marble.x-18,run.marble.y,36,65*(1-t));ctx.globalAlpha=1}ctx.restore();if(transition){const t=Math.min(1,((transition.pausedAt||performance.now())-transition.start)/transition.duration);ctx.save();ctx.translate(120,141);ctx.rotate(t*Math.PI*2);ctx.strokeStyle='#ffca43';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,12+90*t,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle=`rgba(6,3,18,${transition.kind==='exit'?t*.75:(1-t)*.75})`;ctx.fillRect(0,0,240,282)}}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;const previous=run;
  if(transition&&playing()){const elapsed=now-transition.start;if(elapsed>=transition.duration){if(transition.kind==='exit'){run=nextLevel(run);camera=cameraFor(run);transition={kind:'enter',start:now,duration:650};notice.textContent=`enter ${LEVELS[run.levelIndex].name}`;}else{const finished=transition.kind;transition=null;if(finished==='victory')manualPause=true;else notice.textContent='';resumeAudio();}}}
  if(playing()&&!transition&&run.status==='playing')run=step(run,input,dt);
  if(previous.dizzy>0&&run.dizzy===0&&run.marble.x===LEVELS[run.levelIndex].start.x&&run.marble.y===LEVELS[run.levelIndex].start.y)notice.textContent='dizzy cleared · safe reset';
  if(run.failure&&run.lives<previous.lives){failUntil=now+600;sound('hit');notice.textContent=`${run.failure}! try that lane again.`}
  if(run.superJumps>previous.superJumps){sound('pickup');notice.textContent='super bounce charged'}
  if(!transition&&run.status==='cleared'){cancelBounce();transition={kind:'exit',start:now,duration:650};notice.textContent=`level clear · ${LEVELS[run.levelIndex+1].name}`;sound('win')}
  else if(!transition&&run.status==='won'&&!manualPause){cancelBounce();transition={kind:'victory',start:now,duration:650};notice.textContent='all four long runs cleared';sound('win')}
  else if(run.status==='won'&&!transition){manualPause=true}
  else if(run.status==='lost'){notice.textContent=`${run.failure||'run'} ended · restart to try again`;manualPause=true}
  camera=smoothCamera(camera,cameraFor(run),dt);syncUI();draw();requestAnimationFrame(frame)}showPhase('splash');syncUI();requestAnimationFrame(frame);
