import { WORLD, LEVELS, newRun, nextLevel, step, cameraFor } from './game.js';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),levelText=document.querySelector('#level'),livesText=document.querySelector('#lives'),timerText=document.querySelector('#timer'),notice=document.querySelector('#notice');
let run=newRun(),input={x:0,y:0,jump:false,super:false},last=performance.now(),tiltActive=false,paused=false,menuOpen=false,audioOn=true,audio=null,failUntil=0;
const keys=new Set();const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function sound(kind){if(!audioOn)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.connect(g).connect(audio.destination);const map={jump:[330,.07,'square'],super:[660,.12,'sine'],pickup:[880,.1,'triangle'],hit:[90,.18,'sawtooth'],win:[520,.24,'sine']};const [f,d,t]=map[kind]||map.jump;o.frequency.setValueAtTime(f,audio.currentTime);if(kind==='hit')o.frequency.exponentialRampToValueAtTime(35,audio.currentTime+d);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.type=t;o.start();o.stop(audio.currentTime+d)}catch{audioOn=false;document.querySelector('#audio').textContent='audio unavailable'}}
function music(){if(!audioOn)return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();if(audio._mm)return;audio._mm=setInterval(()=>{if(!paused&&run.status==='playing')sound('pickup')},1800)}catch{}};
function updateKeyboard(){input.x=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);input.y=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0)}
function jump(superJump=false){input.jump=true;input.super=superJump;sound(superJump?'super':'jump');setTimeout(()=>{input.jump=false;input.super=false},0)}
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);updateKeyboard()}if(e.key===' '){e.preventDefault();jump(e.shiftKey)}if(e.key==='Escape'){menuOpen=!menuOpen;syncMenu()} });addEventListener('keyup',e=>{keys.delete(e.key);updateKeyboard()});
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*WORLD.width,y=(e.clientY-r.top)/r.height*520;input={...input,x:Math.abs(x-160)>Math.abs(y-260)?Math.sign(x-160):0,y:Math.abs(y-260)>=Math.abs(x-160)?Math.sign(y-260):0};music()});canvas.addEventListener('pointerup',()=>{if(!tiltActive){input.x=0;input.y=0}});
async function enableTilt(){try{if(typeof DeviceOrientationEvent==='undefined')throw Error();if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error();tiltActive=true;document.querySelector('#tilt').textContent='tilt on'}catch{tiltActive=false;notice.textContent='tilt unavailable — use arrows, WASD, or board edges'}}addEventListener('deviceorientation',e=>{if(!tiltActive||e.gamma==null||e.beta==null)return;input.x=clamp(e.gamma/25,-1,1);input.y=clamp(e.beta/25,-1,1)});
document.querySelector('#tilt').onclick=enableTilt;document.querySelector('#restart').onclick=()=>{run=newRun(run.levelIndex);paused=false;notice.textContent='';syncUI();music()};document.querySelector('#pause').onclick=()=>{paused=!paused;syncUI()};document.querySelector('#jump').onclick=()=>jump(false);document.querySelector('#super').onclick=()=>jump(true);document.querySelector('#audio').onclick=()=>{audioOn=!audioOn;document.querySelector('#audio').textContent=audioOn?'audio on':'audio off';if(audioOn)music()};document.querySelector('#waffle').onclick=()=>{menuOpen=!menuOpen;syncMenu()};document.querySelector('#theme').onclick=()=>{const light=document.documentElement.dataset.theme==='light';document.documentElement.dataset.theme=light?'dark':'light';document.querySelector('#theme').textContent=light?'☾':'☀'};document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';
function syncMenu(){document.querySelector('#menu').hidden=!menuOpen}function syncUI(){const l=LEVELS[run.levelIndex];levelText.textContent=`level ${String(run.levelIndex+1).padStart(2,'0')} / ${l.name}`;livesText.textContent='● '.repeat(run.lives).trim()||'—';timerText.textContent=run.remaining.toFixed(1);document.querySelector('#super').textContent=`super bounce · ${run.superJumps}`;document.querySelector('#pause').textContent=paused?'resume':'pause'}
function circle(x,y,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}function draw(){const css=getComputedStyle(document.documentElement),bg=css.getPropertyValue('--board'),line=css.getPropertyValue('--line'),accent=css.getPropertyValue('--accent'),text=css.getPropertyValue('--text'),danger=css.getPropertyValue('--danger');ctx.fillStyle=bg;ctx.fillRect(0,0,320,520);const camera=cameraFor(run);ctx.save();ctx.translate(0,-camera);ctx.strokeStyle=line;ctx.lineWidth=1;for(let y=Math.floor(camera/22)*22;y<camera+542;y+=22){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(320,y);ctx.stroke()}for(let x=22;x<320;x+=22){ctx.beginPath();ctx.moveTo(x,camera);ctx.lineTo(x,camera+520);ctx.stroke()}const l=LEVELS[run.levelIndex];ctx.fillStyle=text;l.obstacles.forEach(r=>ctx.fillRect(r.x,r.y,r.w,r.h));circle(l.goal.x,l.goal.y,WORLD.goalRadius,accent);ctx.fillStyle=text;ctx.font='20px Helvetica';ctx.fillText('exit',l.goal.x-18,l.goal.y+6);run.powerups.forEach(p=>{if(!p.collected){circle(p.x,p.y,14,accent);ctx.fillStyle=bg;ctx.font='20px Helvetica';ctx.fillText('★',p.x-10,p.y+7)}});run.enemies.forEach(e=>circle(e.x,e.y,e.r,danger));if(run.airborne>0){circle(run.marble.x,run.marble.y+10,10,'rgba(0,0,0,.35)')}const g=ctx.createRadialGradient(run.marble.x-5,run.marble.y-6,2,run.marble.x,run.marble.y,14);g.addColorStop(0,'#fff');g.addColorStop(.25,'#ffe234');g.addColorStop(.6,'#ff4612');g.addColorStop(1,'#6f35ff');circle(run.marble.x,run.marble.y-(run.airborne>0?12:0),WORLD.marbleRadius,g);if(performance.now()<failUntil){const t=(failUntil-performance.now())/600;ctx.globalAlpha=t;ctx.fillStyle=danger;if(run.failure==='explode'){for(let i=0;i<12;i++){const a=i*Math.PI/6;circle(run.marble.x+Math.cos(a)*(1-t)*70,run.marble.y+Math.sin(a)*(1-t)*70,7,danger)}}else if(run.failure==='crumble'){for(let i=0;i<8;i++)ctx.fillRect(run.marble.x-24+i*6,run.marble.y+(1-t)*45+(i%2)*8,5,5)}else{ctx.fillRect(run.marble.x-18,run.marble.y,36,65*(1-t))}ctx.globalAlpha=1}ctx.restore()}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;const previous=run;if(!paused&&run.status==='playing')run=step(run,input,dt);if(run.failure&&run.lives<previous.lives){failUntil=now+600;sound('hit');notice.textContent=`${run.failure}! try that lane again.`}if(run.superJumps>previous.superJumps){sound('pickup');notice.textContent='super bounce charged'}if(run.status==='cleared'){notice.textContent=`level clear · ${LEVELS[run.levelIndex+1].name}`;sound('win');paused=true;setTimeout(()=>{run=nextLevel(run);paused=false;notice.textContent=''},900)}else if(run.status==='won'){notice.textContent='all four long runs cleared';sound('win');paused=true}else if(run.status==='lost'){notice.textContent=`${run.failure||'run'} ended · restart to try again`;paused=true}syncUI();draw();requestAnimationFrame(frame)}syncUI();requestAnimationFrame(frame);
