// The physical R1 display is 240×282. Rendering scales this logical viewport only; the world remains larger and scrolls beneath it.
export const VIEWPORT = { width: 320, height: 376, physicalWidth: 240, physicalHeight: 282 };
export const WORLD = { width: 320, height: 1400, marbleRadius: 12, goalRadius: 19, unit: 22 };
export const CAMERA_LEAD = { forward: 38, backward: -24, neutral: 0 };
const wall = (x, y, w, h = WORLD.unit) => ({ x, y, w, h });
const level = (name, start, goal, obstacles, enemies, powerups, time) => ({ name, start, goal, obstacles, enemies, powerups, time });
export const LEVELS = [
  level('first roll', { x: 54, y: 1334 }, { x: 267, y: 66 }, [wall(30,1210,185),wall(125,1018,165),wall(30,835,208),wall(96,640,194),wall(30,450,205),wall(150,255,140)], [], [{x:266,y:1075}], 75),
  level('switchback', { x: 52, y: 1335 }, { x: 270, y: 62 }, [wall(30,1245,210),wall(82,1085,206),wall(30,925,200),wall(105,760,184),wall(30,590,205),wall(110,410,178),wall(30,225,188),wall(202,925,WORLD.unit,88)], [{x:264,y:1150,r:14,axis:'y',span:74,speed:.9}], [{x:54,y:700}], 82),
  level('crossfire', { x: 52, y: 1335 }, { x: 269, y: 60 }, [wall(30,1260,215),wall(90,1100,198),wall(30,940,202),wall(95,780,193),wall(30,620,201),wall(104,455,185),wall(30,290,195),wall(145,941,WORLD.unit,76),wall(62,620,WORLD.unit,66)], [{x:258,y:1180,r:14,axis:'y',span:68,speed:1.2},{x:65,y:520,r:14,axis:'x',span:55,speed:1.05}], [{x:262,y:860},{x:56,y:350}], 88),
  level('marble storm', { x: 52, y: 1335 }, { x: 270, y: 60 }, [wall(30,1270,174),wall(113,1120,175),wall(30,975,189),wall(98,830,190),wall(30,680,198),wall(121,530,167),wall(30,370,198),wall(116,210,172),wall(52,980,WORLD.unit,76),wall(252,720,WORLD.unit,70),wall(145,531,WORLD.unit,76)], [{x:245,y:1210,r:14,axis:'x',span:78,speed:1.55},{x:55,y:740,r:14,axis:'y',span:75,speed:1.35},{x:245,y:350,r:14,axis:'x',span:65,speed:1.7}], [{x:55,y:1040},{x:262,y:575}], 96)
];
export function newRun(levelIndex = 0) { const l = LEVELS[levelIndex]; return { levelIndex, marble:{...l.start,vx:0,vy:0}, enemies:l.enemies.map(e=>({...e,origin:e[e.axis],direction:1})), powerups:l.powerups.map(p=>({...p,collected:false})), remaining:l.time,lives:3,status:'playing',airborne:0,jumpCooldown:0,jumpKind:null,superJumps:0,lastDirection:{x:0,y:-1},failure:null }; }
export function circlesOverlap(a,ar,b,br){return Math.hypot(a.x-b.x,a.y-b.y)<ar+br;}
export function pointInExpandedRect(p,r,pad){return p.x>r.x-pad&&p.x<r.x+r.w+pad&&p.y>r.y-pad&&p.y<r.y+r.h+pad;}
export function moveEnemies(enemies,dt){return enemies.map(e=>{const n={...e};n[e.axis]+=n.direction*n.speed*dt*60;if(Math.abs(n[e.axis]-n.origin)>n.span){n.direction*=-1;n[e.axis]=n.origin+Math.sign(n[e.axis]-n.origin)*n.span}return n})}
function failureFor(run){return ['explode','crumble','melt'][(run.levelIndex+run.lives)%3];}
function collisionAllowed(obstacle, run){const clearance=run.jumpKind==='super'?WORLD.unit*3:WORLD.unit;return run.airborne>0&&obstacle.h<=clearance;}
export function requestJump(run, useSuper=false){if(run.status!=='playing'||run.airborne>0||run.jumpCooldown>0)return run;const canSuper=useSuper&&run.superJumps>0;const kind=canSuper?'super':'normal',distance=canSuper?WORLD.unit*3:WORLD.unit;const d=run.lastDirection;const marble={...run.marble,x:Math.max(WORLD.marbleRadius,Math.min(WORLD.width-WORLD.marbleRadius,run.marble.x+d.x*distance)),y:Math.max(WORLD.marbleRadius,Math.min(WORLD.height-WORLD.marbleRadius,run.marble.y+d.y*distance))};return {...run,marble,airborne:canSuper?.62:.38,jumpCooldown:.48,jumpKind:kind,superJumps:run.superJumps-(canSuper?1:0)};}
export function step(run,input,dt){if(run.status!=='playing')return run;let active=input.jump?requestJump(run,input.super):run;const l=LEVELS[active.levelIndex],m={...active.marble};m.vx=(m.vx+input.x*.21*dt*60)*Math.pow(.89,dt*60);m.vy=(m.vy+input.y*.21*dt*60)*Math.pow(.89,dt*60);m.x+=m.vx*dt*60;m.y+=m.vy*dt*60;const mag=Math.hypot(input.x,input.y);const lastDirection=mag>.1?{x:input.x/mag,y:input.y/mag}:active.lastDirection;const enemies=moveEnemies(active.enemies,dt);const powerups=active.powerups.map(p=>!p.collected&&circlesOverlap(m,WORLD.marbleRadius,p,14)?{...p,collected:true}:p);const superJumps=active.superJumps+powerups.filter((p,i)=>p.collected&&!active.powerups[i].collected).length;const hitWall=m.x<WORLD.marbleRadius||m.x>WORLD.width-WORLD.marbleRadius||m.y<WORLD.marbleRadius||m.y>WORLD.height-WORLD.marbleRadius||l.obstacles.some(r=>!collisionAllowed(r,active)&&pointInExpandedRect(m,r,WORLD.marbleRadius));const hitEnemy=active.airborne<=0&&enemies.some(e=>circlesOverlap(m,WORLD.marbleRadius,e,e.r));if(hitWall||hitEnemy)return {...active,lives:active.lives-1,marble:{...l.start,vx:0,vy:0},enemies,powerups,superJumps,lastDirection,status:active.lives<=1?'lost':'playing',failure:failureFor(active),airborne:0,jumpKind:null};if(circlesOverlap(m,WORLD.marbleRadius,l.goal,WORLD.goalRadius))return {...active,marble:m,enemies,powerups,superJumps,status:active.levelIndex===LEVELS.length-1?'won':'cleared'};const remaining=Math.max(0,active.remaining-dt);return {...active,marble:m,enemies,powerups,superJumps,remaining,lastDirection,airborne:Math.max(0,active.airborne-dt),jumpCooldown:Math.max(0,active.jumpCooldown-dt),jumpKind:Math.max(0,active.airborne-dt)>0?active.jumpKind:null,status:remaining===0?'lost':'playing',failure:remaining===0?failureFor(active):active.failure};}
export function nextLevel(run){return newRun(Math.min(run.levelIndex+1,LEVELS.length-1));}
export function cameraFor(run, viewportHeight=VIEWPORT.height){const look=run.lastDirection.y<-.15?CAMERA_LEAD.forward:run.lastDirection.y>.15?CAMERA_LEAD.backward:CAMERA_LEAD.neutral;return Math.max(0,Math.min(WORLD.height-viewportHeight,run.marble.y-viewportHeight/2+look));}
